name: scraper-instagram

on:
  [push]

run-selenium-tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.10]
        poetry-version: [1.0.10]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install app dependencies
        run: poetry install
      - name: Run main.py (Selenium tests)
        run: poetry run python WebscrapingInstagram.py